version: "2.33"

services:
  app:
    build: .
    ports:
      - "8080:8080" # "Container-Port-Numer : Host-Port-Number"
    networks:
      - s-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: telusko
    ports:
      - 5433:5432
    networks:
      - s-network
    volumes:
      - postgres-s-data:/var/lib/postgresql/data

networks:
  s-network:
    driver: bridge

volumes:
  postgres-s-data:
